-- Script to populate congregations
-- Run this in your Supabase SQL Editor

INSERT INTO congregations (name, sector) VALUES
('SEDE', '1'),
('VARGEM GRANDE', '1'),
('PARAIBUNA', '1'),
('JAMBEIRO', '1'),
('SALESÓPOLIS', '1'),
('TELLES', '1'),
('SAN MARINO', '2'),
('PQ. PLANALTO', '2'),
('ESTORIL', '2'),
('INDEPENDÊNCIA', '2'),
('ALTO SÃO PEDRO', '2'),
('CHÁCARAS SILVESTRE', '2'),
('PQ. TRÊS MARIAS', '2'),
('NAT. DA SERRA', '2'),
('MARMELADA', '2'),
('SAP. MIRIM', '3'),
('S. B DO SAPUCAÍ', '3'),
('JOSÉ DA ROSA', '3'),
('SANTANA', '4'),
('A. DE SANTANA', '4'),
('CH. DAS OLIVEIRAS', '4'),
('JD. MINAS GERAIS', '4'),
('ÁGUAS DE CANINDU', '4'),
('MIRANTE BUQUIRINHA', '4'),
('FREITAS II', '4'),
('JD. GRANJA', '5'),
('JD. SOUTO', '5'),
('JD. UIRÁ', '5'),
('SÃO LEOPOLDO', '6'),
('SÃO JUDAS', '6'),
('CAPUAVA', '6'),
('JD. DO LAGO', '6'),
('PINHEIRINHO', '6'),
('VILA ADRIANA', '6'),
('SANTA JÚLIA', '6'),
('VILA TESOURO', '7'),
('VILA INDUSTRIAL', '7'),
('JD. ISMÊNIA', '7'),
('JD. PAULISTA', '7'),
('SÃO VICENTE', '8'),
('JD. AMERICANO', '8'),
('JD. MOTORAMA', '8'),
('PARARANGABA', '8'),
('P. N. ESPERANÇA', '9'),
('P. N. HORIZONTE', '9'),
('VILA ARAÚJO', '9'),
('PARAÍSO DO SOL', '9'),
('DOM BOSCO', '9'),
('SANTA HERMÍNIA', '9'),
('JD. PRIMAVERA', '9'),
('J. INDUSTRIAS', '10'),
('CHÁCARAS REUNIDAS', '10'),
('URBANOVA', '10'),
('RIO CUMPRIDO', '10'),
('GALO BRANCO', '11'),
('SANTA INÊS I', '11'),
('SANTA INÊS II', '11'),
('JD. SÃO JOSÉ', '11'),
('COQUEIRO', '11'),
('P. INDUSTRIAL', '12'),
('JD. MORUMBI', '12'),
('JD. ORIENTE', '12'),
('N. BRASILEIRA', '12'),
('VALE DO SOL', '12'),
('JD. PETRÓPOLIS', '12'),
('JD. IMPERIAL', '13'),
('REPUBLICA', '13'),
('JD. COLONIAL', '13'),
('RESIDENCIAL UNIÃO', '13'),
('JD. SATÉLITE I', '14'),
('JD. SATÉLITE II', '14'),
('B. DOS EUCALIPTOS', '14'),
('PQ. INTERLAGOS', '14'),
('JD. AEROPORTO', '14'),
('C. ALEMÃES', '15'),
('B. DOS IPÊS', '15'),
('D. PEDRO I', '15'),
('V. DAS FLORES', '15'),
('D. PEDRO II', '15'),
('J. MARIANA I', '16'),
('SANTA CECÍLIA I', '16'),
('JD. HELENA', '16'),
('SETVILLE', '16');
